steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/blog-vibes:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/blog-vibes:$COMMIT_SHA']

# Step to run database migrations as a temporary Cloud Run Job
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    JOB_NAME="blog-vibes-migrate-temp-$BUILD_ID" # Use BUILD_ID for uniqueness
    gcloud run jobs create $JOB_NAME \
      --image=gcr.io/$PROJECT_ID/blog-vibes:$COMMIT_SHA \
      --region=us-central1 \
      --add-cloudsql-instance=${_CLOUD_SQL_CONNECTION_NAME} \
      --set-env-vars=DATABASE_URL=postgresql://${_DB_USER}:$(gcloud secrets versions access latest --secret=DB_PASSWORD)@/${_DB_NAME}?host=/cloudsql/${_CLOUD_SQL_CONNECTION_NAME} \
      --set-secrets=SECRET_KEY=SECRET_KEY:latest,GEMINI_API_KEY=GEMINI_API_KEY:latest \
      --command=flask \
      --args="db,upgrade" \
      --no-traffic # Don't serve traffic, just define the job
    gcloud run jobs execute $JOB_NAME --wait
    gcloud run jobs delete $JOB_NAME --quiet # Clean up the temporary job

# Main deployment step
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - 'run'
  - 'deploy'
  - 'blog-vibes'
  - '--image'
  - 'gcr.io/$PROJECT_ID/blog-vibes:$COMMIT_SHA'
  - '--platform'
  - 'managed'
  - '--region'
  - 'us-central1' # You can change this to your desired region
  - '--allow-unauthenticated' # Adjust based on your authentication needs
  - '--add-cloudsql-instance'
  - '${_CLOUD_SQL_CONNECTION_NAME}'
  - '--set-env-vars'
  - 'DATABASE_URL=postgresql://${_DB_USER}:$(gcloud secrets versions access latest --secret=DB_PASSWORD)@/${_DB_NAME}?host=/cloudsql/${_CLOUD_SQL_CONNECTION_NAME}'
  - '--set-secrets'
  - 'SECRET_KEY=SECRET_KEY:latest,GEMINI_API_KEY=GEMINI_API_KEY:latest'
images:
- 'gcr.io/$PROJECT_ID/blog-vibes:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _CLOUD_SQL_CONNECTION_NAME: 'blog-vibes-465122:us-central1:blog-vibes-db' # REPLACE THIS
  _DB_USER: 'blog_app' # REPLACE THIS
  _DB_PASSWORD: 'projects/$PROJECT_ID/secrets/DB_PASSWORD/versions/latest' # Reference to Secret Manager
  _DB_NAME: 'blog_db' # REPLACE THIS
